-- Application bindings
a.bind("SUPER + RETURN", "Terminal", "acdn-launch-terminal")
a.bind("SUPER + ALT + RETURN", "Tmux", "acdn-launch-terminal-tmux")
a.bind("SUPER + SHIFT + RETURN", "Browser", "zen-browser")
a.bind("SUPER + SHIFT + F", "File manager", "nautilus")
a.bind("SUPER + SHIFT + B", "Browser", "zen-browser")
a.bind("SUPER + SHIFT + ALT + B", "Browser (private)", "zen-browser -private-window")
a.bind("SUPER + SHIFT + M", "Spotify", "spotify")
a.bind("SUPER + SHIFT + O", "Obsidian", "obsidian")
a.bind("SUPER + SHIFT + SLASH", "Passwords", "1password")
